src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\News;
use App\Entity\Calendar;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

use function Symfony\Component\String\u;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[Gedmo\Loggable()]
class User implements UserInterface, PasswordAuthenticatedUserInterface, \Serializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Gedmo\Versioned]
    private $email;

    #[ORM\Column(type: 'json')]
    #[Gedmo\Versioned]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'boolean', options: ["default" => "0"])]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'creator', targetEntity: News::class)]
    private $news;

    #[ORM\ManyToOne(targetEntity: Group::class, inversedBy: 'users')]
    private $mainGroup;

    #[ORM\Column(type: 'boolean', options: ["default" => "0"])]
    private $adminMode = false;

    #[ORM\Column(type: 'string', length: 255)]
    #[Gedmo\Versioned]
    private $firstname;

    #[ORM\Column(type: 'string', length: 255)]
    #[Gedmo\Versioned]
    private $lastname;

    #[ORM\Column(type: 'datetime_immutable')]
    #[Gedmo\Timestampable(on: "create")]
    private $createdAt;

    #[ORM\ManyToOne(targetEntity: Rank::class, inversedBy: 'users')]
    private $mainRank;

    #[ORM\Column(type: 'boolean', options: ["default" => "0"])]
    #[Gedmo\Versioned]
    private $isDesactivated = false;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Gedmo\Versioned]
    private $locale;

    #[ORM\OneToMany(mappedBy: 'creator', targetEntity: Calendar::class)]
    private $calendars;

    #[ORM\OneToMany(mappedBy: 'sender', targetEntity: Notification::class)]
    private $notificationsSent;

    #[ORM\OneToMany(mappedBy: 'receiver', targetEntity: Notification::class, orphanRemoval: true)]
    private $notifications;

    #[ORM\ManyToMany(targetEntity: SubGroup::class, mappedBy: 'users')]
    private $subGroups;

    public function __construct()
    {
        $this->news = new ArrayCollection();
        $this->calendars = new ArrayCollection();
        $this->adminMode = false;
        $this->notificationsSent = new ArrayCollection();
        $this->notifications = new ArrayCollection();
        $this->subGroups = new ArrayCollection();
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->email,
            $this->password,
        ) = unserialize($serialized);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, News>
     */
    public function getNews(): Collection
    {
        return $this->news;
    }

    public function addNews(News $news): self
    {
        if (!$this->news->contains($news)) {
            $this->news[] = $news;
            $news->setCreator($this);
        }

        return $this;
    }

    public function removeNews(News $news): self
    {
        if ($this->news->removeElement($news)) {
            // set the owning side to null (unless already changed)
            if ($news->getCreator() === $this) {
                $news->setCreator(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Calendar>
     */
    public function getCalendars(): Collection
    {
        return $this->calendars;
    }

    public function addCalendar(Calendar $calendar): self
    {
        if (!$this->calendars->contains($calendar)) {
            $this->calendars[] = $calendar;
            $calendar->setCreator($this);
        }

        return $this;
    }

    public function removeCalendar(Calendar $calendar): self
    {
        if ($this->calendars->removeElement($calendar)) {
            // set the owning side to null (unless already changed)
            if ($calendar->getCreator() === $this) {
                $calendar->setCreator(null);
            }
        }

        return $this;
    }

    public function getMainGroup(): ?Group
    {
        return $this->mainGroup;
    }

    public function setMainGroup(?Group $mainGroup): self
    {
        $this->mainGroup = $mainGroup;

        return $this;
    }

    public function getAdminMode(): ?bool
    {
        return $this->adminMode;
    }

    public function setAdminMode(bool $adminMode): self
    {
        if (!$this->hasRole('ROLE_ADMIN')) {
            $adminMode = false;
        }
        $this->adminMode = $adminMode;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullName(): string
    {
        return sprintf('%s %s', u($this->firstname)->title(true), u($this->lastname)->upper());
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getMainRank(): ?Rank
    {
        return $this->mainRank;
    }

    public function setMainRank(?Rank $mainRank): self
    {
        $this->mainRank = $mainRank;

        return $this;
    }

    /**
     * Custom function to check if user has permisssion
     *
     * @param String $permission
     * @return boolean
     */
    public function hasPermission(string $permission): bool
    {
        if ($this->getMainGroup() == null) {
            return false;
        }
        if ($this->getMainRank() == null) {
            return false;
        }
        if ($this->getAdminMode() == true) {
            return true;
        }
        if (in_array(strtolower($permission), array_map('strtolower', $this->getMainRank()->getPermissions()))) {
            return true;
        }
        return false;
    }

    /**
     * Custom function to check if user has role
     *
     * @param String $permission
     * @return boolean
     */
    public function hasRole(string $role): bool
    {
        if (in_array(strtolower($role), array_map('strtolower', $this->getRoles()))) {
            return true;
        }
        return false;
    }

    public function getIsDesactivated(): ?bool
    {
        return $this->isDesactivated;
    }

    public function setIsDesactivated(bool $isDesactivated): self
    {
        $this->isDesactivated = $isDesactivated;

        return $this;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(?string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotificationsSent(): Collection
    {
        return $this->notificationsSent;
    }

    public function addNotificationsSent(Notification $notificationsSent): self
    {
        if (!$this->notificationsSent->contains($notificationsSent)) {
            $this->notificationsSent[] = $notificationsSent;
            $notificationsSent->setSender($this);
        }

        return $this;
    }

templates/_cells/adminGroupActions.html.twig
{% if currentPath != path('admin_group_view', {'id': group.id}) %}
<a href="{{ path('admin_group_view', {'id': group.id}) }}" class="btn btn-primary btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_view{% endtrans %}"><i class="far fa-eye"></i></a>
{% endif %}
<a href="{{ path('admin_group_edit', {'id': group.id}) }}" class="btn btn-success btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_edit{% endtrans %}"><i class="far fa-edit"></i></a>
<a href="{{ path('admin_group_delete', {'id': group.id}) }}" class="btn btn-danger btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_delete{% endtrans %}" onclick="return confirm('{% trans %}confirm_ok_delete{% endtrans %}')"><i class="fa fa-trash"></i></a>

templates/_cells/adminLogsActions.html.twig
<a href="{{ path('admin_logs_view', {'filename': filename}) }}" class="btn btn-success btn-sm mx-1" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_view{% endtrans %}"><i class="fas fa-eye"></i></a>
<a href="{{ path('admin_logs_download', {'filename': filename}) }}" target="_blank" class="btn btn-info btn-sm mx-1" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_download{% endtrans %}"><i class="fas fa-file-download"></i></a>
<a href="{{ path('admin_logs_delete', {'filename': filename}) }}" class="btn btn-danger btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_delete{% endtrans %}" onclick="return confirm('{% trans %}confirm_ok_delete{% endtrans %}')"><i class="fa fa-trash"></i></a>

templates/_cells/adminRankActions.html.twig
{% if currentPath != path('admin_group_rank_view', {'id': rank.id}) %}
<a href="{{ path('admin_group_rank_view', {'id': rank.id}) }}" class="btn btn-primary btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_view{% endtrans %}"><i class="far fa-eye"></i></a>
{% endif %}
<a href="{{ path('admin_group_rank_edit', {'id': rank.id}) }}" class="btn btn-success btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_edit{% endtrans %}"><i class="far fa-edit"></i></a>
<a href="{{ path('admin_group_rank_delete', {'id': rank.id}) }}" class="btn btn-danger btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_delete{% endtrans %}" onclick="return confirm('{% trans %}confirm_ok_delete{% endtrans %}')"><i class="fa fa-trash"></i></a>
<a href="{{ path('admin_group_rank_copy', {'id': rank.id}) }}" class="btn btn-info btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_copy{% endtrans %}"><i class="fas fa-copy"></i></a>

templates/_cells/adminUserActions.html.twig
{% if currentPath != path('admin_user_view', {'id': user.id}) %}
<a href="{{ path('admin_user_view', {'id': user.id}) }}" class="btn btn-primary btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_view{% endtrans %}"><i class="far fa-eye"></i></a>
{% endif %}
<a href="{{ path('admin_user_edit', {'id': user.id}) }}" class="btn btn-success btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_edit{% endtrans %}"><i class="far fa-edit"></i></a>
{% if user.isDesactivated %}
    <a href="{{ path('admin_user_disable', {'id': user.id}) }}" class="btn btn-warning btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_user_enable{% endtrans %}"><i class="fas fa-user-check"></i></a>
{% else %}
    <a href="{{ path('admin_user_disable', {'id': user.id}) }}" class="btn btn-danger btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_user_disable{% endtrans %}"><i class="fas fa-user-times"></i></a>
{% endif %}
<a href="{{ path('app_home', { _want_to_be_this_user: user.email }) }}" class="btn btn-info btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_become_user{% endtrans %}"><i class="fas fa-user-secret"></i></a>

templates/_cells/adminUserInformations.html.twig
<ul class="list-group list-group-flush">
  <li class="list-group-item list-group-item-dark">{% trans %}title_full_name{% endtrans %} : {{user.fullName}}</li>
  <li class="list-group-item list-group-item-dark">{% trans %}title_email{% endtrans %} : <span class="hidethis">{{user.email}}</span></li>
  <li class="list-group-item list-group-item-dark">{% trans %}title_roles{% endtrans %} : {% for r in user.roles %}[ {{ r }} ] {% endfor %}</li>
  <li class="list-group-item list-group-item-dark">{% trans %}title_group{% endtrans %} : {{user.mainGroup ? user.mainGroup.name : 'value_no_group'|trans}}</li>
  <li class="list-group-item list-group-item-dark">{% trans %}title_rank{% endtrans %} : {{user.mainRank ? user.mainRank.name : 'value_no_group'|trans}}</li>
  <li class="list-group-item list-group-item-dark">{% trans %}title_subgroups{% endtrans %} : {% if user.subGroups %}
    {% for sg in user.subGroups %}{{ sg.name}}{% if loop.last == false %}, {% endif %}{% endfor %}
    {% else %}{{'value_no_subgroups'|trans}}{% endif %}</li>
  <li class="list-group-item list-group-item-dark">{% trans %}title_verified{% endtrans %} : {{user.isVerified ? 'value_yes'|trans : 'value_no'|trans }}</li>
  <li class="list-group-item list-group-item-dark">{% trans %}title_desactivated{% endtrans %} : {{user.isDesactivated ? 'value_yes'|trans : 'No'}}</li>
  <li class="list-group-item list-group-item-dark">{% trans %}title_created_at{% endtrans %} : {{user.createdAt |date('_datetime.format'|trans)}}</li>
  <li class="list-group-item list-group-item-dark">{% trans %}title_admin_mode{% endtrans %} : {{user.adminMode ? 'value_yes'|trans : 'value_no'|trans }}</li>
</ul>

templates/_cells/adminUserTable.html.twig
<div class="table-responsive">
  <table class="table table-dark table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          {% if noemail is not defined %}
          <th scope="col">{% trans %}title_email{% endtrans %}</th>
          {% endif %}
          <th scope="col">{% trans %}title_full_name{% endtrans %}</th>
          <th scope="col">{% trans %}title_group{% endtrans %}</th>
          <th scope="col">{% trans %}title_verified{% endtrans %}</th>
          <th scope="col">{% trans %}title_created_at{% endtrans %}</th>
          {% if noaction is not defined %}
          <th scope="col">{% trans %}title_actions{% endtrans %}</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
          {% for i in users %}
              <tr>
                  <th scope="row">{{i.id}}</th>
                  {% if noemail is not defined %}
                  <td><span class="hidethis">{{i.email}}</span></td>
                  {% endif %}
                  <td>
                    {{ i.fullName }} {% if 'ROLE_ADMIN' in i.roles %}<span class="text-warning">({% trans %}title_user_admin{% endtrans %})</span>{% endif %}
                    {% if i.isDesactivated %}<span class="text-danger">({% trans %}title_desactivated{% endtrans %})</span>{% endif %}
                  </td>
                  <td>{{i.mainGroup ? i.mainGroup.shortName : 'value_no_group'|trans}}, {{i.mainRank ? i.mainRank.shortName : 'value_no_rank'|trans}}</td>
                  <td>{{i.isVerified ? 'value_yes'|trans : 'value_no'|trans}}</td>
                  <td>{{i.createdAt |date('_datetime.format'|trans)}}</td>
                  {% if noaction is not defined %}
                  <td>
                    {% include '_cells/adminUserActions.html.twig' with {'user': i} %}
                  </td>
                  {% endif %}
              </tr>
          {% endfor %}
      </tbody>
  </table>
</div>

templates/_cells/calendarActions.html.twig
{% if is_granted('view', document) %}
    {% if currentPath != path('document_view', {'id': document.id}) and noview is not defined %}
    <a href="{{ path('document_view', {'id': document.id}) }}" class="btn btn-primary btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_view{% endtrans %}"><i class="far fa-eye"></i></a>
    {% endif %}
    {% if is_granted('edit', document) and noedit is not defined %}
    <a href="{{ path('document_edit', {'id': document.id}) }}" class="btn btn-success btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_edit{% endtrans %}"><i class="far fa-edit"></i></a>
    {% endif %}
    {% if is_granted('delete', document) and nodelete is not defined %}
    <a href="{{ path('document_delete', {'id': document.id}) }}" class="btn btn-danger btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_delete{% endtrans %}" onclick="return confirm('{% trans %}confirm_ok_delete{% endtrans %}')"><i class="fa fa-trash"></i></a>
    {% endif %}
    {% if document.allowShare and noshare is not defined %}
    <a href="{{ path('share', {'share': document.share}) }}" class="btn btn-info btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_share_link{% endtrans %}" target="_blank"><i class="fa fa-link"></i></a>
    {% endif %} 
    {% if is_granted('archive', document) and noarchive is not defined %}
    <a href="{{ path('document_archive', {'id': document.id}) }}" class="btn btn-{% if document.archive %}danger{% else %}info{% endif %} btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% if document.archive %}{% trans %}tooltip_unarchive{% endtrans %}{% else %}{% trans %}tooltip_archive{% endtrans %}{% endif %}" onclick="return confirm('Are you ok to {% if document.archive %}un{% endif %}archive this ?')"><i class="fas fa-archive"></i></a>
    {% endif %}
    
    {% if addtofolder is defined %}
        <a href="{{ path('folder_document_add', {'id': addtofolder, 'Document': document.id}) }}" class="btn btn-success btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_add_to_folder{% endtrans %}"><i class="fas fa-folder-plus"></i></a>
    {% endif %}
    {% if removefromfolder is defined %}
        <a href="{{ path('folder_document_remove', {'id': removefromfolder, 'Document': document.id}) }}" class="btn btn-danger btn-sm" data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_remove_from_folder{% endtrans %}" onclick="return confirm('{% trans %}confirm_ok_remove_from_folder{% endtrans %}')"><i class="fas fa-folder-minus"></i></a>
    {% endif %}

{% else %}
<span class="text-danger"><i class="fas fa-eye-slash"></i></span>
{% endif %}

templates/_cells/calendarTable.html.twig
{% set slicelimit = (limit is defined)? limit : null %}  
{% set counter = 0 %}

{% if calendars|length > 0 %}
<div class="table-responsive">
  <table class="table table-dark table-striped table-hover align-middle">
    <thead>
      <tr>
        <th scope="col">{% trans %}title_title{% endtrans %}</th>        
        <th scope="col">{% if noauthor is not defined %}{% trans %}title_author{% endtrans %} / {% endif %}{% trans %}title_date{% endtrans %}</th>
        {% if noaction is not defined %}
          <th scope="col">{% trans %}title_actions{% endtrans %}</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>      
      {% for i in calendars |slice(0, slicelimit) %} 
      {% set counter = counter + 1 %}
          <tr>
            <td>              
              <a href="{{ path('calendar_view', {'id': i.id}) }}" class="text-{{ (i.archive)? 'danger' : 'primary' }}" {% if i.archive %} data-bs-toggle="tooltip" data-placement="top"  title="{% trans %}tooltip_archived{% endtrans %}" {% endif %} >`{{i.title | u.truncate(20, '...')}}`</a>
              {% if i.status is defined %} 
                <br /><small>{% trans %}title_status{% endtrans %}:</small>
                <small>{{ i.status|trans }}</small>
              {% endif %}
              {% if i.removingDate is defined %} 
                <br /><small>{% trans %}title_can_be_removed_at{% endtrans %}:</small>
                <small class="text-{% if date(i.removingDate) < date() %}danger{% endif %}{% if date(i.removingDate) == date() %}warning{% endif %}{% if date(i.removingDate) > date() %}success{% endif %}">{{ i.removingDate|date('_datetime.format'|trans) }}</small>
              {% endif %}
              {% if i.user is defined %}            
                <br /><small>{% trans %}title_user{% endtrans %}:</small>
                <small><a href="{{ path('user_view', {'id': i.user.id}) }}" >{{ i.user.firstname  | u.truncate(2, '.')}} {{ i.user.lastname }}</a></small>
              {% endif %}
            </td>
            <td>
              {% if noauthor is not defined %}
                <a href="{{ path('user_view', {'id': i.creator.id }) }}" >{{i.creator.firstname | u.truncate(2, '.')}} {{i.creator.lastname}}, {{i.creator.mainGroup ? i.creator.mainGroup.shortname : 'value_no_group'|trans}}</a><br />
              {% endif %}            
              {{i.createdAt |date('_datetime.format'|trans)}}
            </td>
            {% if noaction is not defined %}
              <td>
                {% include '_cells/calendarActions.html.twig' with {'calendar': i} %}
              </td>
            {% endif %}
          </tr>      
    {% endfor %} 
    </tbody>
  </table>
</div>

{% if slicelimit is not null and calendars|length > slicelimit %}
  <div class="row my-2">
    <div class="col">
        <a class="btn btn-primary btn-sm" href="{{ path('calendar_list') }}">{% trans %}button_view_more{% endtrans %}</a>
    </div>
  </div>
{% endif %}

{% else %}
  <p>{% trans %}no_data{% endtrans %}</p>
{% endif %}

templates/_cells/historyDisplay.html.twig
<h5>{% trans %}title_order_from_last_old{% endtrans %}</h5>
<hr>
{% for i in history %}
<div class="row border m-2">
  <div class="col-md-8">
    <p class="text-info">{{ ('history_' ~ i.action)|trans }} : {{ i.loggedAt |date('_datetime.format'|trans) }} 
      {% if i.username %}
        {% trans %}title_author{% endtrans %}: {% if '@' in i.username and app.user.adminmode == false  %} {% trans %}hided_email{% endtrans %} {% else %} {{ i.username }} {% endif %}
      {% else %}
        {% trans %}title_noauthor{% endtrans %}
      {% endif %}
    </p> 
    {% if notype is not defined %}
      <p>{{ i.objectClass }} (# {{ i.objectId }})</p>
    {% endif %}   
    <p>{{ ('title_data_' ~ i.action)|trans }}</p>    
    <div class="table-responsive">
      <table class="table table-dark table-striped table-bordered">
        <thead>
          <tr>
            <th scope="col">{% trans %}title_field{% endtrans %}</th>
            <th scope="col">{% trans %}title_value{% endtrans %}</th>
          </tr>
        </thead>
        {% for field, value in i.data %}
        <tr>
          <td>
            {{ ('form_label_' ~ field)|trans }}
          </td>
          <td>
            {% if value is iterable %}
                {% for x, y in value %}
                  {{ x }} : {% if y is iterable %}{'iterable_value'|trans }}{% else %}{{ y }}{% endif %}
                {% endfor %}
            {% elseif value.timestamp is defined %}
              {{ value|date('_datetime.format'|trans) }}
            {% else %}
              {{ value? value|raw : 'value_no_value'|trans }}
            {% endif %}
            
          </td>
        </tr>
        {% endfor %} 
      </table>
    </div>
  </div>
</div>
{% endfor %}

templates/_cells/userInformations.html.twig
<ul class="list-group list-group-flush">
  <li class="list-group-item list-group-item-dark">{% trans %}title_full_name{% endtrans %} : <a href="{{ path('user_view', {'id': user.id}) }}">{{user.fullName}}</a></li>
  <li class="list-group-item list-group-item-dark">{% trans %}title_group{% endtrans %} : {{user.mainGroup ? user.mainGroup.name : 'value_no_group'|trans }}</li>  
  <li class="list-group-item list-group-item-dark">{% trans %}title_rank{% endtrans %} : {{user.mainRank ? user.mainRank.name : 'value_no_rank'|trans}}</li>
  <li class="list-group-item list-group-item-dark">{% trans %}title_subgroups{% endtrans %} : {% if user.subGroups %}
    {% for sg in user.subGroups %}{{ sg.name}}{% if loop.last == false %}, {% endif %}{% endfor %}
    {% else %}{{'value_no_subgroups'|trans}}{% endif %}</li>
  <li class="list-group-item list-group-item-dark">{% trans %}title_created_at{% endtrans %} : {{user.createdAt |date('_datetime.format'|trans)}}</li>
</ul>

templates/_cells/userTable.html.twig
<div class="table-responsive">
  <table class="table table-dark table-striped">
    <thead>
      <tr>        
        <th scope="col">{% trans %}title_full_name{% endtrans %}</th>
        <th scope="col">{% trans %}title_group{% endtrans %} / {% trans %}title_rank{% endtrans %}</th>
        <th scope="col">{% trans %}title_actions{% endtrans %}</th>
      </tr>
    </thead>
    <tbody>
        {% for i in users %}
            <tr>                
                <td>{{ i.fullName }}</td>
                <td>{{i.mainGroup ? i.mainGroup.shortName : 'value_no_group'|trans}}<br><small>{{i.mainRank ? i.mainRank.name : 'value_no_rank'|trans}}</small></td>
                <td>
                  {% include '_cells/userActions.html.twig' with {'user': i} %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
  </table>
</div>